### PR TITLE
WIP V3 Extension Update

### PR DESCRIPTION
**Pull request by Raistlfiren**
This is about completed. There are a few things to fix, add, and remove.

### CODE REVIEW

**Comment by xiaohutai** [comment]
Hi @Raistlfiren,

Awesome stuff.

Is this for Bolt 3? If so, then I might make:
- a `master` and a `release/3.0` branch for Bolt 3.x.x
- a `release/2.2` branch for Bolt 2.2.x

I've merged the other pull request with a few fixes, do you think you can rebase that or do we need to try and fix some merge conflicts?

**Comment by Raistlfiren** [comment]
@xiaohutai 

This is for Bolt 3. Sorry for not clarifying. A summary of what I have done is listed below - 
- Refactored the storage layer to use the new one in Bolt 3
- Abstracted `filters`, `contains`, `page[number]`, `page[size]`, and `includes` into a ParamConverter
- Changed invalid and not found errors to exceptions that are caught by the app and displayed as a response
- Put Menu method into ContentController because content methods were overwriting menu methods
- Refactored out `$app['paths']['baseurl']` to `$app['paths']['hosturl']`
  - $app['paths']['baseurl'] doesn't add port

A few things to do are
- [ ] Add tests
- [x] Remove unneeded methods in APIHelper that were factored out
- [x] Search works for **SINGLE** items, **NOT** multiple content types right now (There isn't a way to do that with the new storage layer yet.)
  - Maybe use legacy search
- [x] Pagination is also not supported with the current Bolt storage layer yet so all results are fetched and arrays are sliced.
- [ ] Fetching single items does not show previous or next link for results
- [x] PSR-2 compliance
- [x] `fields` are not fetched in JSONAPIConverter(Param Converter)

**Comment by xiaohutai** [comment]
Hello @Raistlfiren ,

I went ahead and merged the other pull request (Bolt 2.2 version). Does this pull request need to be applied on top of that, or should I have branched it off before that pull request #16 ?

Thanks again for you hard work!

**Comment by Raistlfiren** [comment]
@xiaohutai - OK, I think this is ready for V3 now. There are still a few more tasks that would be nice to get completed like testing, but that can be done over time. I did notice an issue with the total results being returned when running `COUNT(*)`. I am looking into the issue. I think it has to do with excluding `groupBy` in the query.

This should also resolve some of the issues as well like #14 - all routes now use the JSONAPI parameters, #11 - I used hostUrl for the baseUrl and it carries the port # with it, and #8 - checks datetime types to see if they are null before trying to apply a format to the object.

**Pull request merged**
